[package]
name = "useless-svg"
version = "0.2.0"
authors = ["Bastien de Luca <dev@de-luca.io>"]
edition = "2018"

[dependencies]
md5 = "0.7.0"
rand = "0.7.3"
env_logger = "0.7"
actix-http = "1.0.1"
actix-web = "2.0.0"
actix-rt = "1.0.0"
lazy_static = "1.4.0"
bit-vec = "0.6.2"
