[package]
name = "useless-svg"
version = "0.1.0"
authors = ["Bastien de Luca <dev@de-luca.io>"]
edition = "2018"

[dependencies]
tera = "1.3.1"
rand = "0.7.3"
env_logger = "0.7"
actix-http = "1.0.1"
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde = "1.0.114"
lazy_static = "1.4.0"
